---
my_auth_apikey: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32643865626430396666623737653937643033356439323365326566653162666339613038306636
  3762663766373435623730383635366135626336323765640a633966643362643137343564636632
  33623663613532636265386162653438373035343539363763353335646165356630363236396162
  6366316237373162340a646233656666646234613535356162376634653364336531666534313134
  66383632326330346465313363353935383439323737376261383065303539386232363463656465
  39626432383065326130313735393131643766303839326666303037613462373433643463616165
  64383838666264633964623434373739306637356663636135383938316437663963363036343737
  30666336646263383830326163343966326435333334663039343762663764663733386632653338
  39656233663964303534363736303635653831633033646637323934666265636334623763363837
  62373564343364373732626366366163633465373065313365323038373636616264346662643962
  636463336363616530323362626563373239
